### ISSUE TITLE
Fix memory leak on development container

### ISSUE THREAD

**Issue by hally9k** [vital-software/vitalizer#102]
Crashes intermittently, terrible DX.

This is most likely caused by the HMR files accumulating in memory.
To observe this navigate to `localhost:3000/webpack-dev-server` and save the project to watch the files accumulate.

Some conversation around this issue here: https://github.com/webpack/webpack/issues/6929
May well be the way that we are using the webpack node API...

**Comment by teriu** [comment]
Tentatively resolved in #101
