### ISSUE TITLE
Ensure empty line between it() functions, and between describe() functions in linter/prettier settings

### ISSUE THREAD

**Issue by teriu** [vital-software/vitalizer#36]

**Comment by hally9k** [comment]
Generic padding-blocks linting rules aren't able to specify it or describe blocks.  Issue added here to see if the jest plugin wants to deal to this case: https://github.com/jest-community/eslint-plugin-jest/issues/17

**Comment by teriu** [comment]
This issue was moved to vital-software/eslint-config#5
