### ISSUE TITLE
Fix dependency clashing and upgrade Storybook.

### ISSUE THREAD

**Issue by hally9k** [vital-software/vitalizer#98]
The `webpack-dev-server` dependency gets removed from the client project's `node_modules` when @storybook@3.4.0 is installed.

This is because yarn hoisting doesn't behave the same when dependencies clash. 

Potential solution from strothj here: https://github.com/storybooks/storybook/issues/3344

**Comment by teriu** [comment]
Resolved in https://github.com/vital-software/trackboard/pull/1120
